// Devises supportées — internationales et africaines
export const CURRENCIES = {
  EUR: { label: "Euro", symbol: "€" },
  USD: { label: "Dollar américain", symbol: "$" },
  GBP: { label: "Livre sterling", symbol: "£" },
  CHF: { label: "Franc suisse", symbol: "CHF" },
  CAD: { label: "Dollar canadien", symbol: "$" },
  AED: { label: "Dirham des Émirats", symbol: "د.إ" },
  SAR: { label: "Riyal saoudien", symbol: "ر.س" },
  QAR: { label: "Riyal qatari", symbol: "ر.ق" },
  KWD: { label: "Dinar koweïtien", symbol: "د.ك" },
  MAD: { label: "Dirham marocain", symbol: "DH" },
  DZD: { label: "Dinar algérien", symbol: "DA" },
  TND: { label: "Dinar tunisien", symbol: "DT" },
  EGP: { label: "Livre égyptienne", symbol: "E£" },
  LYD: { label: "Dinar libyen", symbol: "LD" },
  SDG: { label: "Livre soudanaise", symbol: "SDG" },
  SOS: { label: "Shilling somalien", symbol: "Sh" },
  DJF: { label: "Franc djiboutien", symbol: "Fdj" },
  SSP: { label: "Livre sud-soudanaise", symbol: "SSP" },
  XOF: { label: "Franc CFA (BCEAO)", symbol: "CFA" },
  XAF: { label: "Franc CFA (BEAC)", symbol: "FCFA" },
  NGN: { label: "Naira nigérian", symbol: "₦" },
  GHS: { label: "Cedi ghanéen", symbol: "GH₵" },
  GMD: { label: "Dalasi gambien", symbol: "D" },
  GNF: { label: "Franc guinéen", symbol: "GFr" },
  SLE: { label: "Leone sierra-léonais", symbol: "Le" },
  LRD: { label: "Dollar libérien", symbol: "L$" },
  MRU: { label: "Ouguiya mauritanienne", symbol: "UM" },
  CVE: { label: "Escudo cap-verdien", symbol: "$" },
  KES: { label: "Shilling kényan", symbol: "KSh" },
  TZS: { label: "Shilling tanzanien", symbol: "TSh" },
  UGX: { label: "Shilling ougandais", symbol: "USh" },
  RWF: { label: "Franc rwandais", symbol: "FRw" },
  BIF: { label: "Franc burundais", symbol: "FBu" },
  ETB: { label: "Birr éthiopien", symbol: "Br" },
  ERN: { label: "Nakfa érythréen", symbol: "Nfk" },
  MGA: { label: "Ariary malgache", symbol: "Ar" },
  SCR: { label: "Roupie seychelloise", symbol: "Rs" },
  MUR: { label: "Roupie mauricienne", symbol: "Rs" },
  ZAR: { label: "Rand sud-africain", symbol: "R" },
  NAD: { label: "Dollar namibien", symbol: "N$" },
  BWP: { label: "Pula botswanais", symbol: "P" },
  ZMW: { label: "Kwacha zambien", symbol: "ZK" },
  MWK: { label: "Kwacha malawite", symbol: "MK" },
  MZN: { label: "Metical mozambicain", symbol: "MT" },
  AOA: { label: "Kwanza angolais", symbol: "Kz" },
  CDF: { label: "Franc congolais", symbol: "FC" },
  ZWG: { label: "Zimbabwe Gold", symbol: "ZiG" },
  STN: { label: "Dobra santoméen", symbol: "Db" },
  SZL: { label: "Lilangeni swazi", symbol: "E" },
  LSL: { label: "Loti lesothan", symbol: "L" },
};

export const CURRENCY_GROUPS = [
  { label: "Internationales", codes: ["EUR", "USD", "GBP", "CHF", "CAD", "AED", "SAR", "QAR", "KWD"] },
  { label: "Afrique du Nord", codes: ["MAD", "DZD", "TND", "EGP", "LYD", "SDG", "DJF", "SOS", "SSP"] },
  { label: "Afrique de l'Ouest", codes: ["XOF", "NGN", "GHS", "XAF", "GMD", "GNF", "SLE", "LRD", "MRU", "CVE"] },
  { label: "Afrique de l'Est", codes: ["KES", "TZS", "UGX", "RWF", "BIF", "ETB", "ERN", "MGA", "SCR", "MUR"] },
  {
    label: "Afrique centrale & australe",
    codes: ["ZAR", "NAD", "BWP", "ZMW", "MWK", "MZN", "AOA", "CDF", "ZWG", "STN", "SZL", "LSL"],
  },
];

export const CURRENCY_SYMBOLS = Object.fromEntries(
  Object.entries(CURRENCIES).map(([code, c]) => [code, c.symbol])
);